development:
  adapter: postgresql
  encoding: unicode
  database: homeday_dev
  pool: 2
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: homeday
  pool: 2
  username:
  password: